// src/components/Contratos/UserContractsStyle.js

const style = {
    pageTitle: {
        fontSize: '2rem',
        fontWeight: 600,
        color: '#333',
        marginBottom: '25px',
        textAlign: 'center',
        width: "100%",
    },
    userContractsSection: {
        // marginTop: '60px',
        width: '100%',
        // maxWidth: '1200px',
        marginLeft: 'auto',
        marginRight: 'auto',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    controlsPanel: {
        width: '100%',
        background: '#fdfdfd',
        border: '1px solid #e9ecef',
        borderRadius: '12px',
        padding: '20px',
        marginBottom: '25px',
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    filtersContainer: {
        display: 'flex',
        gap: '20px',
        justifyContent: 'center',
        flexWrap: 'wrap',
        width: '100%',
    },
    filterInput: {
        padding: '12px 15px',
        border: '1px solid #ddd',
        borderRadius: '8px',
        fontSize: '1rem',
        width: '250px',
        maxWidth: '100%',
    },
    filterSelect: {
        padding: '12px 15px',
        border: '1px solid #ddd',
        borderRadius: '8px',
        fontSize: '1rem',
        width: '250px',
        maxWidth: '100%',
        cursor: 'pointer',
    },
    paginationContainer: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '10px 0',
        width: '100%',
        flexWrap: 'wrap',
        gap: '20px',
        borderTop: '1px solid #e9ecef',
    },
    paginationControls: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
    },
    paginationInput: {
        width: '60px',
        padding: '8px 10px',
        textAlign: 'center',
        border: '1px solid #ddd',
        borderRadius: '8px',
    },
    paginationInfo: {
        fontWeight: '500',
        color: '#555',
    },
    paginationNav: {
        display: 'flex',
        gap: '10px',
    },
    paginationButton: {
        padding: '8px 16px',
        border: '1px solid #ddd',
        borderRadius: '8px',
        background: '#fff',
        cursor: 'pointer',
        fontWeight: '600',
        transition: 'background-color 0.2s, color 0.2s',
    },
    paginationButtonDisabled: {
        cursor: 'not-allowed',
        opacity: 0.5,
    },
    contractsTable: {
        width: '100%',
        borderCollapse: 'collapse',
        boxShadow: '0 4px 15px rgba(0,0,0,0.08)',
        borderRadius: '12px',
        overflow: 'hidden',
        textAlign: 'left',
    },
    contractsTableTh: {
        backgroundColor: '#f8f9fa',
        padding: '15px 20px',
        fontWeight: 600,
        color: '#333',
        borderBottom: '2px solid #e9ecef',
        whiteSpace: 'nowrap',
    },
    contractsTableTd: {
        padding: '15px 20px',
        borderBottom: '1px solid #e9ecef',
        color: '#555',
        background: '#fff',
        verticalAlign: 'middle',
    },
    statusBadge: { padding: '5px 12px', borderRadius: '15px', fontSize: '0.85rem', fontWeight: 500, color: '#fff', display: 'inline-block' },
    statusPendente: { backgroundColor: '#ffc107', color: '#333' },
    statusValorizando: { backgroundColor: '#28a745' },
    statusCancelado: { backgroundColor: '#dc3545' },
    statusRecomprado: { backgroundColor: '#17a2b8' },
    statusFinalizado: { backgroundColor: '#6c757d' },
    tableRow: {
        cursor: 'pointer',
        transition: 'background-color 0.2s ease-in-out',
    },
};

export default style;