const style = {
    extratosPageContainer: {
        width: '100%',
        maxWidth: '1200px',
        margin: '0 auto',
        padding: '30px 20px',
        boxSizing: 'border-box',
    },
    pageHeader: {
        textAlign: 'center',
        marginBottom: '40px',
    },
    pageTitle: {
        fontSize: '2.2rem',
        fontWeight: 600,
        color: '#333',
        marginBottom: '10px',
    },
    pageSubtitle: {
        fontSize: '1.1rem',
        color: '#666',
        maxWidth: '600px',
        margin: '0 auto',
    },
    filtersContainer: {
        display: 'flex',
        justifyContent: 'center',
        gap: '15px',
        marginBottom: '30px',
        flexWrap: 'wrap',
    },
    filterInput: {
        padding: '12px 15px',
        border: '1px solid #ddd',
        borderRadius: '8px',
        fontSize: '0.95rem',
        minWidth: '180px',
        flex: 1,
    },
    filterSelect: {
        padding: '12px 15px',
        border: '1px solid #ddd',
        borderRadius: '8px',
        fontSize: '0.95rem',
        backgroundColor: '#fff',
        cursor: 'pointer',
        flex: 1,
        minWidth: '150px',
        maxWidth: '200px'
    },
    tableContainer: {
        backgroundColor: 'white',
        padding: '20px',
        borderRadius: '12px',
        boxShadow: '0 8px 25px rgba(0,0,0,0.1)',
        display: 'flex',
        flexDirection: 'column',
    },
    tableWrapper: {
        overflowX: 'auto',
        width: '100%',
    },
    extratosTable: {
        width: '100%',
        borderCollapse: 'collapse',
    },
    tableTh: {
        padding: '15px',
        textAlign: 'left',
        whiteSpace: 'nowrap',
        fontSize: '0.8rem',
        color: '#888',
        textTransform: 'uppercase',
        fontWeight: 600,
        borderBottom: '2px solid #f0f2f5',
    },
    tableTr: {
        borderBottom: '1px solid #f5f5f5',
    },
    tableTd: {
        padding: '15px',
        textAlign: 'left',
        whiteSpace: 'nowrap',
        color: '#555',
        fontSize: '0.95rem',
    },
    positiveAmount: {
        color: '#28a745',
        fontWeight: 500,
    },
    negativeAmount: {
        color: '#dc3545',
        fontWeight: 500,
    },
    noResultsTd: {
        textAlign: 'center',
        padding: '40px',
        color: '#777',
        fontSize: '1rem',
    },
    paginationContainer: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: '20px',
        marginTop: '15px',
        gap: '8px',
    },
    pageButton: {
        width: '36px',
        height: '36px',
        border: '1px solid #ddd',
        borderRadius: '8px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: '#555',
        backgroundColor: 'white',
        cursor: 'pointer',
        fontWeight: 500,
        transition: 'all 0.2s ease',
    },
    pageButtonActive: {
        backgroundColor: '#007bff',
        borderColor: '#007bff',
        color: 'white',
        boxShadow: '0 4px 8px rgba(0, 123, 255, 0.2)',
    },
};

export default style;