const style = {
  featuredContainer: {
    width: "100%",
    height: "100%",
    position: "relative",
    borderRadius: "12px",
    overflow: "hidden",
    color: "white",
    boxShadow: "0 6px 12px rgba(0, 0, 0, 0.08)",
    cursor: "pointer",
  },
  featuredMedia: {
    width: "100%",
    height: "100%",
    position: "absolute",
    top: 0,
    left: 0,
    zIndex: 1,
    backgroundSize: "cover",
    backgroundPosition: "center",
    objectFit: "cover",
    transition: "transform 0.5s ease-in-out",
  },
  featuredOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    padding: "30px",
    transition: "background-color 0.4s ease",
  },
  featuredOverlayHover: {
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  featuredTag: {
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    padding: "5px 12px",
    borderRadius: "15px",
    fontSize: "0.8rem",
    fontWeight: "600",
    alignSelf: "flex-start",
    marginBottom: "10px",
    color: "white",
  },
  featuredTitle: {
    margin: "0",
    fontSize: "1.8rem",
    fontWeight: "700",
    transform: "scale(1)",
    transition: "transform 0.4s ease",
    color: "white",
  },
  featuredTitleHover: {
    transform: "scale(1.05)",
  },
  featuredDescription: {
    margin: "10px 0 0 0",
    fontSize: "1rem",
    maxWidth: "80%",
    lineHeight: "1.5",
    transform: "scale(1)",
    transition: "transform 0.4s ease",
    color: "white",
  },
  featuredDescriptionHover: {
    transform: "scale(1.02)",
  },
  lightOverlay: {
    backgroundColor: "rgba(255, 255, 255, 0.75)",
  },
  lightOverlayHover: {
    backgroundColor: "rgba(255, 255, 255, 0.9)",
  },
  lightTag: {
    backgroundColor: "rgba(0, 0, 0, 0.05)",
    color: "#555",
  },
  lightTitle: {
    color: "#334155",
  },
  lightDescription: {
    color: "#6c757d",
  },
  lightArrow: {
    backgroundColor: "rgba(255, 255, 255, 0.6)",
    color: "#333",
  },
  arrow: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    color: "white",
    border: "none",
    height: "40px",
    width: "40px",
    borderRadius: "50%",
    cursor: "pointer",
    fontSize: "1rem",
    zIndex: 3,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background-color 0.3s ease",
  },
  leftArrow: {
    left: "15px",
  },
  rightArrow: {
    right: "15px",
  },
};

export default style;
