const styles = {
    notificationsContainer: {
      width: "100%",
      maxWidth: "900px",
      margin: "40px auto",
      padding: "40px",
      backgroundColor: "#fff",
      borderRadius: "20px",
      boxShadow: "0 8px 32px rgba(0, 0, 0, 0.05)",
      fontFamily: "'Poppins', sans-serif",
    },
    pageHeader: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      borderBottom: "1px solid #f0f0f0",
      paddingBottom: "20px",
      marginBottom: "30px",
    },
    pageTitle: {
      fontSize: "2rem",
      fontWeight: "700",
      color: "#1e293b",
      margin: 0,
      flex: 1,
      textAlign: 'center',
    },
    backButton: {
      background: '#f8fafc',
      border: '1px solid #e2e8f0',
      color: '#475569',
      width: '40px',
      height: '40px',
      borderRadius: '50%',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    markAllAsReadButton: {
      background: 'transparent',
      border: 'none',
      color: '#3b82f6',
      fontWeight: '600',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
    },
    notificationList: {
      display: "flex",
      flexDirection: "column",
      gap: "15px",
    },
    notificationItem: {
      display: "flex",
      alignItems: "flex-start",
      padding: "20px",
      borderRadius: "12px",
      border: "1px solid #f0f0f0",
      cursor: "pointer",
      transition: "transform 0.2s ease, box-shadow 0.2s ease, background-color 0.2s ease",
    },
    notificationItemUnread: {
      backgroundColor: '#f0f9ff',
    },
    notificationItemHover: {
      transform: "translateY(-3px)",
      boxShadow: "0 6px 20px rgba(0, 0, 0, 0.06)",
      backgroundColor: '#fafcff'
    },
    notificationIconContainer: {
      position: 'relative',
      marginRight: "20px",
    },
    notificationIcon: {
      width: "50px",
      height: "50px",
      borderRadius: "50%",
      backgroundColor: "#e0e7ff",
      color: "#4f46e5",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "1.2rem",
    },
    unreadDot: {
      position: 'absolute',
      top: '0',
      right: '0',
      width: '12px',
      height: '12px',
      backgroundColor: '#3b82f6',
      borderRadius: '50%',
      border: '2px solid white',
    },
    notificationContent: {
      flex: 1,
    },
    notificationHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: "5px",
    },
    notificationTitle: {
      margin: 0,
      fontSize: "1.1rem",
      fontWeight: "600",
      color: "#1e293b",
    },
    notificationTime: {
      fontSize: "0.8rem",
      color: "#94a3b8",
    },
    notificationText: {
      margin: 0,
      color: "#64748b",
      lineHeight: 1.6,
    },
    seeMore: {
      color: "#3b82f6",
      fontWeight: "600",
    },
    notificationDetailContainer: {
      width: "100%",
      maxWidth: "900px",
      margin: "40px auto",
      padding: "40px",
      backgroundColor: "#fff",
      borderRadius: "20px",
      boxShadow: "0 8px 32px rgba(0, 0, 0, 0.05)",
    },
    detailTime: {
      fontSize: "0.9rem",
      color: "#94a3b8",
      fontWeight: '500',
    },
    detailContent: {
      padding: "20px 0",
    },
    detailText: {
      fontSize: "1.1rem",
      lineHeight: 1.8,
      color: "#334155",
      whiteSpace: 'pre-wrap',
    },
    redirectButton: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '10px',
      marginTop: '30px',
      padding: '12px 24px',
      backgroundColor: '#4f46e5',
      color: '#fff',
      textDecoration: 'none',
      borderRadius: '12px',
      fontWeight: '600',
      transition: 'transform 0.2s ease, background-color 0.2s ease',
    },
  };
  
  export default styles;