const colors = {
  primary: "#122C4F",
  activeBg: "#2a4a7d",
  text: "#e0e0e0",
  logoText: "#fff",
};

const dimensions = {
  expanded: "400px",
  collapsed: "88px",
  mobileWidth: "280px",
  transitionSpeed: "0.3s",
};

const style = {
  // --- ESTILOS GERAIS E DE DESKTOP ---
  sidebar: {
    backgroundColor: colors.primary,
    padding: "10px 14px",
    height: "100vh",
    position: "sticky",
    top: 0,
    left: 0,
    display: "flex",
    flexDirection: "column",
    transition: `width ${dimensions.transitionSpeed} ease, transform ${dimensions.transitionSpeed} ease`,
    zIndex: 1000,
  },
  sidebarExpanded: {
    width: dimensions.expanded,
  },
  sidebarCollapsed: {
    width: dimensions.collapsed,
  },
  sidebarHeader: {
    display: "flex",
    alignItems: "center",
    position: "relative",
    paddingBottom: "20px",
    cursor: "pointer",
  },
  sidebarLogo: {
    minWidth: "60px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.activeBg,
    color: colors.logoText,
    fontSize: "1.5rem",
    fontWeight: "bold",
    height: "50px",
    borderRadius: "6px",
    overflow: "hidden",
    padding: 0,
  },
  sidebarTitle: {
    display: "flex",
    flexDirection: "column",
    marginLeft: "10px",
    opacity: 1,
    transition: `opacity ${dimensions.transitionSpeed} ease`,
    whiteSpace: "nowrap",
  },
  sidebarTitleCollapsed: {
    opacity: 0,
    pointerEvents: "none",
  },
  titleText: {
    fontSize: "1.4rem",
    fontWeight: 600,
    color: colors.logoText,
  },
  sidebarToggle: {
    position: "absolute",
    top: "50%",
    right: "-12px",
    transform: "translateY(-50%)",
    height: "25px",
    width: "25px",
    backgroundColor: colors.activeBg,
    color: colors.logoText,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    cursor: "pointer",
    fontSize: "0.8rem",
    zIndex: 101,
  },
  navLinks: {
    listStyle: "none",
    padding: 0,
    margin: "20px 0",
    flexGrow: 1,
    overflowY: "auto",
    overflowX: "hidden",
  },
  subMenu: {
    listStyle: "none",
    paddingLeft: "20px",
    paddingTop: 0,
    paddingBottom: 0,
    margin: 0,
    overflow: "hidden",
    backgroundColor: "rgba(0,0,0,0.15)",
    borderRadius: "6px",
    maxHeight: "0",
    transition:
      "max-height 0.3s ease-in-out, padding-top 0.3s ease-in-out, padding-bottom 0.3s ease-in-out",
  },
  subMenuOpen: {
    maxHeight: "500px",
    paddingTop: "10px",
    paddingBottom: "10px",
  },
  subMenuItem: {
    height: "45px",
    paddingLeft: "10px",
    marginBottom: "5px",
  },
  navLink: {
    display: "flex",
    alignItems: "center",
    height: "50px",
    borderRadius: "6px",
    textDecoration: "none",
    color: colors.text,
    marginBottom: "10px",
    transition: `background-color ${dimensions.transitionSpeed} ease`,
  },
  navLinkActive: {
    backgroundColor: colors.activeBg,
    color: colors.logoText,
  },
  navLinkIcon: {
    minWidth: "60px",
    fontSize: "1.2rem",
    textAlign: "center",
  },
  linkText: {
    opacity: 1,
    transition: `opacity ${dimensions.transitionSpeed} ease`,
    whiteSpace: "nowrap",
  },
  linkTextCollapsed: {
    opacity: 0,
    pointerEvents: "none",
  },
  sidebarFooter: {
    position: "relative", // Necessário para posicionar o pop-up
    paddingTop: "10px",
    marginTop: "auto",
    borderTop: `1px solid ${colors.activeBg}`,
  },
  // --- NOVOS ESTILOS PARA O FOOTER E AJUDA ---
  footerContent: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  helpButton: {
    background: "transparent",
    border: "none",
    color: colors.text,
    fontSize: "1.6rem",
    cursor: "pointer",
    width: "50px",
    height: "50px",
    borderRadius: "6px",
    marginLeft: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background-color 0.3s ease",
  },
  helpPopup: {
    position: "absolute",
    bottom: "calc(100% + 10px)", // Posiciona acima do footer
    left: "0",
    width: "100%",
    backgroundColor: "#ffffff",
    color: "#333",
    padding: "20px",
    borderRadius: "8px",
    boxShadow: "0 -4px 15px rgba(0,0,0,0.2)",
    textAlign: "center",
    marginBottom: "10px",
    zIndex: 1100,
    boxSizing: "border-box",
  },
  popupText: {
    margin: "0 0 15px 0",
    fontSize: "1rem",
    color: "#122C4F",
  },
  whatsappButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#25D366",
    color: "#fff",
    padding: "10px 20px",
    borderRadius: "50px",
    textDecoration: "none",
    fontWeight: "bold",
    fontSize: "1rem",
    border: "none",
    cursor: "pointer",
    transition: "background-color 0.3s ease",
  },
  // --- ESTILOS PARA MOBILE ---
  mobileMenuIcon: {
    position: "fixed",
    top: "15px",
    left: "15px",
    zIndex: 1001,
    background: colors.primary,
    color: colors.logoText,
    border: "none",
    borderRadius: "6px",
    width: "50px",
    height: "50px",
    fontSize: "1.5rem",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 2px 10px rgba(0,0,0,0.2)",
  },
  mobileCloseIcon: {
    position: "absolute",
    top: "10px",
    right: "10px",
    background: "transparent",
    color: colors.logoText,
    border: "none",
    fontSize: "1.5rem",
    cursor: "pointer",
    width: "40px",
    height: "40px",
  },
  sidebarMobile: {
    position: "fixed",
    left: 0,
    top: 0,
    height: "100%",
    width: dimensions.mobileWidth,
    transform: "translateX(-100%)",
    boxShadow: "3px 0px 15px rgba(0,0,0,0.2)",
  },
  sidebarMobileOpen: {
    transform: "translateX(0)",
  },
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 999,
  },

  // --- NOVOS ESTILOS PARA O CABEÇALHO MOBILE ---
  sidebarHeaderMobile: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: "20px",
    paddingBottom: "20px",
    cursor: "pointer",
  },
  sidebarTitleMobile: {
    marginLeft: 0,
    marginTop: "15px",
    textAlign: "center",
  },
  titleTextMobile: {
    fontSize: "1.2rem", // Fonte menor para mobile
    fontWeight: 600,
    color: colors.logoText,
  },
};

export default style;