// /src/Components/Register/RegisterStyle.js

const colors = {
  primary: "#007bff",
  primaryDark: "#0056b3",
  background: "#f0f2f5",
  white: "#fff",
  textDark: "#333",
  textLight: "#555",
  border: "#ddd",
  borderLight: "#eee",
  shadow: "rgba(0, 0, 0, 0.1)",
  error: "#dc3545",
  success: "#28a745",
};

const style = {
  registerPage: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "100vh",
    backgroundColor: colors.background,
    padding: "40px 20px",
    fontFamily: "'Segoe UI', 'Roboto', 'Helvetica Neue', sans-serif",
    boxSizing: "border-box",
  },
  registerContainer: {
    width: "100%",
    maxWidth: "850px",
    backgroundColor: colors.white,
    borderRadius: "10px",
    boxShadow: `0 10px 30px ${colors.shadow}`,
    padding: "40px 50px",
    boxSizing: "border-box",
    transition: "height 0.4s ease-in-out",
  },
  form: {
    width: "100%",
    margin: "0 auto",
  },
  progressBarContainer: {
    position: "relative",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "40px",
    width: "80%",
    margin: "0 auto 40px auto",
  },
  progressLine: {
    position: "absolute",
    top: "50%",
    left: 0,
    transform: "translateY(-50%)",
    height: "4px",
    backgroundColor: colors.borderLight,
    width: "100%",
    zIndex: 1,
  },
  progressLineActive: {
    position: "absolute",
    top: "50%",
    left: 0,
    transform: "translateY(-50%)",
    height: "4px",
    backgroundColor: colors.primary,
    zIndex: 2,
    transition: "width 0.4s ease-in-out",
  },
  progressStep: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    zIndex: 3,
    position: "relative",
  },
  progressCircle: (isActive, isCompleted) => ({
    height: "30px",
    width: "30px",
    borderRadius: "50%",
    backgroundColor: colors.white,
    border: `3px solid ${
      isActive || isCompleted ? colors.primary : colors.borderLight
    }`,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    color: isActive || isCompleted ? colors.primary : colors.textLight,
    fontWeight: "bold",
    transition: "border-color 0.4s, color 0.4s",
  }),
  progressLabel: (isActive) => ({
    marginTop: "10px",
    fontSize: "0.9rem",
    fontWeight: isActive ? "bold" : "normal",
    color: isActive ? colors.primary : colors.textLight,
    transition: "all 0.4s",
  }),
  formTitle: {
    textAlign: "center",
    fontSize: "2rem",
    fontWeight: "600",
    color: colors.textDark,
    marginBottom: "10px",
  },
  formSubtitle: {
    textAlign: "center",
    fontSize: "0.95rem",
    color: colors.textLight,
    marginBottom: "30px",
  },
  formRow: {
    display: "flex",
    gap: "20px",
    marginBottom: "20px",
  },
  formField: {
    flex: 1,
    position: "relative",
  },
  docTypeToggle: { display: "flex", gap: "10px", marginBottom: "5px" },
  docLabel: { fontSize: "0.9rem", color: colors.textLight, cursor: "pointer" },
  label: {
    display: "block",
    fontSize: "0.9rem",
    color: colors.textLight,
    marginBottom: "5px",
    fontWeight: "500",
  },
  input: {
    width: "100%",
    padding: "12px 15px",
    fontSize: "1rem",
    border: `1px solid ${colors.border}`,
    borderRadius: "8px",
    boxSizing: "border-box",
    transition: "border-color 0.3s, box-shadow 0.3s",
    outline: "none",
    color: colors.textLight,
  },
  nameFieldContainer: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    width: "100%",
  },
  nameSpinner: {
    position: "absolute",
    right: "15px",
    animation: "spin 1s linear infinite",
    fontSize: "1rem",
    color: colors.primary,
  },
  validateCpfButton: {
    padding: "12px 20px",
    backgroundColor: colors.primary,
    color: colors.white,
    border: "none",
    borderRadius: "8px",
    fontSize: "0.9rem",
    fontWeight: "bold",
    cursor: "pointer",
    transition: "all 0.3s",
    width: '100%',
    height: '48px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  validationContainer: {
    display: 'flex',
    alignItems: 'flex-end',
    flex: 0.5
  },
  select: {
    width: "100%",
    padding: "12px 15px",
    fontSize: "1rem",
    border: `1px solid ${colors.border}`,
    borderRadius: "8px",
    boxSizing: "border-box",
    outline: "none",
    color: colors.textLight,
    backgroundColor: colors.white,
  },
  contactGroup: { display: "flex", gap: "10px", minWidth: 300 },
  countryCodeSelect: {
    flex: "0 0 120px",
    padding: "12px 10px",
    fontSize: "1rem",
    border: `1px solid ${colors.border}`,
    borderRadius: "8px",
    boxSizing: "border-box",
    outline: "none",
    color: colors.textLight,
    backgroundColor: colors.white,
  },
  passwordToggleIcon: {
    position: "absolute",
    right: "15px",
    top: "65%",
    transform: "translateY(-50%)",
    color: "#aaa",
    cursor: "pointer",
    fontSize: "1rem",
  },
  cepField: { display: "flex", alignItems: "center", gap: "10px" },
  cepSpinner: {
    animation: "spin 1s linear infinite",
    display: "inline-block",
    fontSize: "1rem",
    color: colors.primary,
  },
  formNavigation: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: "30px",
  },
  navButton: {
    padding: "12px 30px",
    border: `1px solid ${colors.border}`,
    backgroundColor: colors.white,
    color: colors.textDark,
    borderRadius: "8px",
    fontSize: "1rem",
    fontWeight: "bold",
    cursor: "pointer",
    transition: "all 0.3s",
  },
  submitButton: {
    padding: "12px 30px",
    backgroundColor: colors.primary,
    color: colors.white,
    border: "none",
    borderRadius: "8px",
    fontSize: "1rem",
    fontWeight: "bold",
    cursor: "pointer",
    transition: "background-color 0.3s, opacity 0.3s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    minWidth: "150px",
    minHeight: "48px",
  },
  successButton: {
    backgroundColor: colors.success,
    cursor: "default",
  },
  errorMessage: {
    color: colors.error,
    fontSize: "0.9rem",
    textAlign: "center",
    marginBottom: "15px",
    minHeight: "20px",
  },
};

export default style;