const style = {
    bodyDashboard: {
        width: '100%',
        minHeight: '100vh',
        backgroundColor: '#f0f2f5',
        display: 'flex',
        justifyContent: 'center',
        padding: '20px',
        boxSizing: 'border-box',
    },
    containerDashboard: {
        width: '100%',
        maxWidth: '1400px',
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    headerRow: {
        display: 'flex',
        alignItems: 'center',
        // marginBottom: '20px',
    },
    headerLogo: {
        height: '50px',
        marginRight: '15px',
    },
    headerTitle: {
        color: '#333',
        fontWeight: 500,
        fontSize: '1.5rem',
        margin: 0,
    },
    dashboardRow: {
        display: 'flex',
        gap: '20px',
        width: '100%',
    },
    dashboardRowStretch: {
        alignItems: 'stretch',
    },
    dashboardCard: {
        flex: 1,
        background: 'white',
        borderRadius: '8px',
        boxShadow: '0 4px 8px rgba(0, 0, 0, 0.05)',
        padding: '20px',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        color: '#333',
        borderLeft: '5px solid #007bff',
    },
    dashboardCardHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        marginBottom: '10px',
    },
    cardHeaderH3: {
        fontSize: '0.9rem',
        margin: 0,
        color: '#777',
        fontWeight: 500,
        textTransform: 'uppercase',
    },
    cardHeaderIcon: {
        color: '#aaa',
        cursor: 'pointer',
        fontSize: '1rem',
    },
    dashboardCardValue: {
        fontSize: '1.7rem',
        fontWeight: 'bold',
        marginBottom: '5px',
        color: '#222',
    },
    dashboardCardSecondaryValue: {
        fontSize: '0.85rem',
        color: '#666',
        marginBottom: '15px',
    },
    dashboardCardFooter: {
        display: 'flex',
        alignItems: 'center',
        fontSize: '0.75rem',
        color: '#888',
    },
    cardFooterIcon: {
        marginRight: '5px',
        color: '#5cb85c',
    },
    dashboardGrafico: {
        background: 'white',
        borderRadius: '8px',
        padding: '20px',
        boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
        display: 'flex',
        flexDirection: 'column',
        flex: 1.8,
    },
    dashboardPiechartWrapper: {
        flex: 1.2,
        position: 'relative',
    },
    dashboardPiechart: {
        background: 'white',
        color: '#333',
        borderRadius: '8px',
        padding: '20px',
        boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
        display: 'flex',
        flexDirection: 'column',
        width: '100%',
        height: '100%',
        transition: 'transform 0.4s cubic-bezier(0.25, 0.8, 0.25, 1)',
    },
    dashboardPiechartHover: {
        transform: 'scale(1.02)',
    },
    chartTitle: {
        fontSize: '1.1rem',
        fontWeight: 600,
        color: '#333',
        margin: '0 0 20px 0',
        paddingBottom: '15px',
        borderBottom: '1px solid #eee',
    },
    chartContainer: {
        flexGrow: 1,
        minHeight: '250px',
    },
    expandedContent: {
        position: 'absolute',
        top: '98%',
        left: 0,
        width: '100%',
        backgroundColor: 'white',
        borderRadius: '0 0 8px 8px',
        boxShadow: '0 10px 20px rgba(0,0,0,0.1)',
        padding: '20px',
        zIndex: 10,
        opacity: 0,
        transform: 'translateY(-20px) scaleY(0.9)',
        transformOrigin: 'top center',
        pointerEvents: 'none',
        transition: 'opacity 0.4s ease-out, transform 0.4s ease-out',
    },
    expandedContentVisible: {
        opacity: 1,
        transform: 'translateY(0) scaleY(1)',
        pointerEvents: 'auto',
    },
    dashboardCol: {
        flex: 1,
        display: 'flex',
    },
    dashboardColFull: {
        flex: 1,
        overflow: 'auto',
    },
    dataTableContainer: {
        backgroundColor: 'white',
        padding: '20px',
        borderRadius: '8px',
        boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
    },
    dataTableheader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingBottom: '10px',
        borderBottom: '1px solid #eee',
    },
    dataTableTitle: {
        margin: 0,
        fontSize: '1rem',
        color: '#333',
        fontWeight: 600,
    },
    dataTableControlsIcon: {
        color: '#888',
        cursor: 'pointer',
    },
    dataTableFilters: {
        display: 'flex',
        gap: '15px',
        margin: '15px 0',
    },
    filterBox: {
        backgroundColor: '#f7f7f7',
        border: '1px solid #e0e0e0',
        color: '#555',
        padding: '8px 12px',
        borderRadius: '6px',
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        fontSize: '0.9rem',
        cursor: 'pointer',
    },
    filterBoxIcon: {
        color: '#888',
    },
    tableWrapper: {
        overflowX: 'auto',
        flexGrow: 1,
    },
    dataTable: {
        width: '100%',
        borderCollapse: 'collapse',
    },
    tableHeaderCell: {
        padding: '12px 15px',
        textAlign: 'left',
        whiteSpace: 'nowrap',
        fontSize: '0.75rem',
        color: '#888',
        textTransform: 'uppercase',
        fontWeight: 500,
        borderBottom: '2px solid #eee',
    },
    tableBodyRow: {
        borderBottom: '1px solid #f5f5f5',
    },
    tableCell: {
        padding: '12px 15px',
        textAlign: 'left',
        whiteSpace: 'nowrap',
        color: '#555',
    },
    status: {
        padding: '4px 10px',
        borderRadius: '12px',
        fontWeight: 500,
        fontSize: '0.8rem',
    },
    statusValorizando: {
        color: '#006400',
        backgroundColor: '#e8f5e9',
    },
    statusPago: {
        color: '#155724',
        backgroundColor: '#d4edda',
    },
    statusPendente: {
        color: '#721c24',
        backgroundColor: '#f8d7da',
    },
    paginationContainer: {
        display: 'flex',
        justifyContent: 'center',
        paddingTop: '20px',
        marginTop: 'auto',
        gap: 10,
    },
    pageButton: {
        width: '32px',
        height: '32px',
        border: '1px solid #ddd',
        borderRadius: '4px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: '#555',
        cursor: 'pointer',
        fontWeight: 500,
        border: "none",
        boxShadow: "2px 2px 3px rgba(0,0,0,0.3)"
    },
    pageButtonActive: {
        backgroundColor: '#f0f2f5',
        borderColor: '#ccc',
    },
};

export default style;