const style = {
  bodyDashboard: {
    width: "100%",
    minHeight: "100vh",
    backgroundColor: "#fdfdfd",
    display: "flex",
    justifyContent: "center",
    padding: "40px",
    boxSizing: "border-box",
    fontFamily: "'Poppins', sans-serif",
  },
  containerDashboard: {
    width: "100%",
    maxWidth: "1400px",
    display: "flex",
    flexDirection: "column",
    gap: "40px",
  },
  headerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    boxSizing: "border-box",
    marginBottom: "10px",
  },
  headerLogoContainer: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
  },
  headerLogo: {
    height: "80px",
    marginLeft: "auto",
    marginRight: "auto",
    paddingLeft: "50px",
  },
  notificationBell: {
    position: "relative",
    cursor: "pointer",
    width: "50px",
    height: "50px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  notificationIcon: {
    fontSize: "1.5rem",
    color: "#475569",
    transition: "color 0.2s ease",
  },
  notificationBadge: {
    position: "absolute",
    top: "8px",
    right: "8px",
    backgroundColor: "#ef4444",
    color: "white",
    borderRadius: "50%",
    width: "18px",
    height: "18px",
    fontSize: "0.7rem",
    fontWeight: "bold",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "2px solid white",
    animation: "scaleIn 0.3s ease-out",
  },
  tooltip: {
    position: "absolute",
    bottom: "-35px",
    left: "50%",
    transform: "translateX(-50%)",
    backgroundColor: "#1e293b",
    color: "white",
    padding: "5px 12px",
    borderRadius: "6px",
    fontSize: "0.8rem",
    whiteSpace: "nowrap",
    zIndex: "10",
    animation: "fadeInUpTooltip 0.3s ease-out",
  },
  dashboardRow: { display: "flex", gap: "30px", width: "100%" },

  dashboardCard: {
    flex: 1,
    background: "white",
    borderRadius: "16px",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.05)",
    padding: "30px",
    display: "flex",
    flexDirection: "column",
    color: "#333",
    border: "1px solid #f0f0f0",
    transition: "min-height 0.6s cubic-bezier(0.4, 0, 0.2, 1)",
  },
  dashboardCardCollapsed: { minHeight: "98px" },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    paddingBottom: "15px",
    borderBottom: "1px solid #f1f5f9",
    cursor: "pointer",
  },
  cardHeaderH3: {
    fontSize: "1.1rem",
    margin: 0,
    color: "#1e293b",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "1px",
  },
  cardHeaderArrow: {
    color: "#94a3b8",
    transition: "transform 0.5s cubic-bezier(0.4, 0, 0.2, 1)",
  },
  cardContent: {
    overflow: "hidden",
    transition:
      "max-height 0.6s cubic-bezier(0.4, 0, 0.2, 1), margin-top 0.6s cubic-bezier(0.4, 0, 0.2, 1), opacity 0.5s ease-in-out",
  },
  cardContentExpanded: { maxHeight: "1000px", marginTop: "25px", opacity: 1 },
  cardContentCollapsed: { maxHeight: "52px", marginTop: "15px", opacity: 1 },
  cardInfoList: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  cardInfoItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    fontSize: "1rem",
  },
  cardInfoLabel: { color: "#64748b" },
  cardInfoValue: { fontWeight: "600", fontSize: "1.1rem", color: "#0f172a" },

  mainActionsContainer: {
    display: "flex",
    gap: "30px",
    width: "100%",
    animation: "fadeInUp 0.8s ease-out forwards",
  },
  actionButton: {
    flex: 1,
    position: "relative",
    padding: "40px",
    borderRadius: "20px",
    border: "none",
    textAlign: "left",
    cursor: "pointer",
    overflow: "hidden",
    transition: "transform 0.3s ease, box-shadow 0.3s ease",
    boxShadow: "0 8px 32px rgba(0,0,0,0.08)",
  },
  actionButtonPrimary: {
    background: "linear-gradient(135deg, #2c5282, #3b82f6)",
    color: "white",
  },
  actionButtonSecondary: {
    background: "linear-gradient(135deg, #1e293b, #475569)",
    color: "white",
  },
  actionButtonText: { zIndex: 2, position: "relative" },
  actionButtonTitle: {
    fontSize: "1.8rem",
    fontWeight: "bold",
    margin: "0 0 8px 0",
  },
  actionButtonDescription: {
    fontSize: "1rem",
    margin: 0,
    opacity: 0.8,
    maxWidth: "80%",
  },
  actionButtonIcon: {
    position: "absolute",
    bottom: "-20px",
    right: "-20px",
    fontSize: "100px",
    color: "rgba(255, 255, 255, 0.1)",
    transform: "rotate(-20deg)",
    transition: "transform 0.4s ease",
  },

  dashboardContentBlockLarge: {
    flex: 2,
    position: "relative",
    minHeight: "400px",
  },
  dashboardContentBlockSmall: {
    flex: 1,
    position: "relative",
    minHeight: "400px",
  },

  productsSection: { width: "100%", marginTop: "20px" },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "40px",
  },
  sectionTitle: {
    fontSize: "2.2rem",
    fontWeight: 700,
    color: "#1e293b",
    margin: 0,
  },
  seeMoreButton: {
    background: "transparent",
    color: "#3b82f6",
    border: "none",
    fontWeight: "600",
    fontSize: "1rem",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  productsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "30px",
  },
  productCard: {
    background: "white",
    borderRadius: "16px",
    overflow: "hidden",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.05)",
    transition: "transform 0.3s ease, box-shadow 0.3s ease",
    cursor: "pointer",
    border: "1px solid #f0f0f0",
  },
  productImageContainer: {
    position: "relative",
    height: "350px",
    overflow: "hidden",
  },
  productImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    transition: "transform 0.5s ease",
  },
  productOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background:
      "linear-gradient(to top, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0) 50%)",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    padding: "20px",
    opacity: 0,
    transition: "opacity 0.4s ease",
  },
  productButton: {
    background: "white",
    color: "#1e293b",
    border: "none",
    borderRadius: "50px",
    padding: "12px 24px",
    fontWeight: "600",
    cursor: "pointer",
    transform: "translateY(20px)",
    transition: "transform 0.4s ease, background-color 0.3s",
  },
  productInfo: { padding: "25px" },
  productName: {
    fontSize: "1.25rem",
    fontWeight: 600,
    color: "#1e293b",
    margin: "0 0 8px 0",
  },
  productPrice: { fontSize: "1.1rem", color: "#64748b", margin: 0 },

  "@keyframes fadeInUp": {
    from: { opacity: 0, transform: "translateY(20px)" },
    to: { opacity: 1, transform: "translateY(0)" },
  },
  "@keyframes scaleIn": {
    from: { transform: "scale(0.5)", opacity: 0 },
    to: { transform: "scale(1)", opacity: 1 },
  },
  "@keyframes fadeInUpTooltip": {
    from: { opacity: 0, transform: "translateY(-40%) translateX(-50%)" },
    to: { opacity: 1, transform: "translateY(0) translateX(-50%)" },
  },
};

export default style;
