const style = {
    bodyDashboard: {
        width: '100%',
        minHeight: '100vh',
        backgroundColor: '#f8f9fa',
        display: 'flex',
        justifyContent: 'center',
        padding: '20px',
        boxSizing: 'border-box',
        fontFamily: "'Poppins', sans-serif",
    },
    containerDashboard: {
        width: '100%',
        // maxWidth: '1400px',
        display: 'flex',
        flexDirection: 'column',
        gap: '25px',
    },
    headerRow: {
        display: 'flex',
        alignItems: 'center',
    },
    headerLogo: {
        height: '50px',
        marginRight: '15px',
    },
    dashboardRow: {
        display: 'flex',
        gap: '25px',
        width: '100%'
    },
    dashboardRowStretch: {
        alignItems: 'stretch',
    },
    dashboardCard: {
        flex: 1,
        background: 'white',
        borderRadius: '12px',
        boxShadow: '0 6px 12px rgba(0, 0, 0, 0.08)',
        padding: '25px',
        display: 'flex',
        flexDirection: 'column',
        color: '#333',
        borderLeft: '6px solid #007bff',
        transition: 'transform 0.3s ease, box-shadow 0.3s ease',
    },
    dashboardCardLarge: {
        minHeight: '220px',
        justifyContent: 'flex-start',
    },
    cardHeaderH3: {
        fontSize: '1.1rem',
        margin: 0,
        color: '#334155',
        fontWeight: 600,
        textTransform: 'uppercase',
        letterSpacing: '0.5px',
        width: '100%',
        paddingBottom: '15px',
        borderBottom: '1px solid #f0f2f5',
    },
    cardInfoList: {
        width: '100%',
        marginTop: '25px',
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
    },
    cardInfoItem: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        fontSize: '1rem',
        color: '#6c757d',
        paddingBottom: '8px',
    },
    cardInfoValue: {
        fontWeight: '700',
        fontSize: '1.15rem',
        color: '#007bff',
        backgroundColor: '#f0f7ff',
        padding: '4px 10px',
        borderRadius: '6px',
    },
    dashboardContentBlockLarge: {
        flex: 7,
        background: 'white',
        borderRadius: '12px',
        boxShadow: '0 6px 12px rgba(0, 0, 0, 0.08)',
        position: 'relative',
        minHeight: '400px',
    },
    dashboardContentBlockSmall: {
        flex: 3,
        background: 'white',
        borderRadius: '12px',
        boxShadow: '0 6px 12px rgba(0, 0, 0, 0.08)',
        position: 'relative',
        minHeight: '400px',
    },
    dashboardCol: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
    },
    dashboardColFull: {
        flex: 1,
        overflow: 'auto',
        width: "100%"
    },
    dataTableContainer: {
        backgroundColor: 'white',
        padding: '25px',
        borderRadius: '12px',
        boxShadow: '0 6px 12px rgba(0, 0, 0, 0.08)',
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
    },
    dataTableheader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingBottom: '15px',
        borderBottom: '1px solid #f0f2f5',
    },
    dataTableTitle: {
        margin: 0,
        fontSize: '1.1rem',
        color: '#334155',
        fontWeight: 600,
    },
    dataTableControlsIcon: {
        color: '#888',
        cursor: 'pointer',
    },
    tableWrapper: {
        overflowX: 'auto',
        flexGrow: 1,
        marginTop: '15px',
    },
    dataTable: {
        width: '100%',
        borderCollapse: 'collapse',
    },
    tableHeaderCell: {
        padding: '12px 15px',
        textAlign: 'left',
        whiteSpace: 'nowrap',
        fontSize: '0.8rem',
        color: '#6c757d',
        textTransform: 'uppercase',
        fontWeight: 600,
        borderBottom: '2px solid #f0f2f5',
    },
    tableBodyRow: {
        borderBottom: '1px solid #f8f9fa',
    },
    tableCell: {
        padding: '15px',
        textAlign: 'left',
        whiteSpace: 'nowrap',
        color: '#495057',
        fontSize: '0.95rem',
    },
    paginationContainer: {
        display: 'flex',
        justifyContent: 'center',
        paddingTop: '20px',
        marginTop: 'auto',
        gap: 10,
    },
    pageButton: {
        width: '32px',
        height: '32px',
        border: '1px solid #ddd',
        borderRadius: '4px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: '#555',
        cursor: 'pointer',
        fontWeight: 500,
        border: "none",
        boxShadow: "2px 2px 3px rgba(0,0,0,0.3)"
    },
    pageButtonActive: {
        backgroundColor: '#f0f2f5',
        borderColor: '#ccc',
    },
};

export default style;