const colors = {
  primary: "#007bff",
  success: "#28a745",
  info: "#17a2b8",
  danger: "#dc3545",
  background: "#f8f9fa",
  white: "#fff",
  textDark: "#333",
  textLight: "#555",
  border: "#e9ecef",
  shadow: "rgba(0, 0, 0, 0.08)",
};

const style = {
  page: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "40px 20px",
    backgroundColor: colors.background,
  },
  container: { width: "100%", maxWidth: "900px" },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "30px",
  },
  headerLeft: { display: "flex", alignItems: "center", gap: "20px" },
  backButton: {
    background: colors.white,
    border: `1px solid ${colors.border}`,
    width: "44px",
    height: "44px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1rem",
    color: colors.textDark,
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow: `0 2px 4px ${colors.shadow}`,
  },
  title: {
    fontSize: "2.5rem",
    fontWeight: 700,
    color: colors.textDark,
    margin: 0,
  },
  statusBadge: {
    padding: "8px 18px",
    borderRadius: "20px",
    fontSize: "1rem",
    fontWeight: "bold",
    color: colors.white,
  },
  detailsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "25px",
    marginBottom: "30px",
  },
  metricCard: {
    backgroundColor: colors.white,
    padding: "25px",
    borderRadius: "12px",
    border: `1px solid ${colors.border}`,
    boxShadow: `0 4px 12px ${colors.shadow}`,
  },
  metricLabel: {
    fontSize: "0.9rem",
    color: colors.textLight,
    marginBottom: "8px",
    display: "block",
    fontWeight: 500,
  },
  metricValue: { fontSize: "1.8rem", fontWeight: 700, color: colors.textDark },

  trackingCard: {
    backgroundColor: colors.white,
    padding: "25px",
    borderRadius: "12px",
    border: `1px solid ${colors.border}`,
    boxShadow: `0 4px 12px ${colors.shadow}`,
    marginBottom: "30px",
  },
  trackingTitle: {
    fontSize: "1.5rem",
    fontWeight: 600,
    color: colors.textDark,
    margin: "0 0 15px 0",
  },
  trackingBody: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    fontSize: "1rem",
  },
  trackingLink: {
    display: "inline-block",
    marginTop: "10px",
    padding: "10px 20px",
    backgroundColor: colors.primary,
    color: colors.white,
    textDecoration: "none",
    borderRadius: "8px",
    fontWeight: "bold",
    textAlign: "center",
    transition: "background-color 0.3s",
  },

  mediaSection: {
    display: "flex",
    flexDirection: "column",
    gap: "30px",
    marginBottom: "30px",
  },
  mediaCard: {
    backgroundColor: colors.white,
    padding: "25px",
    borderRadius: "12px",
    border: `1px solid ${colors.border}`,
    boxShadow: `0 4px 12px ${colors.shadow}`,
  },
  mediaTitle: {
    fontSize: "1.5rem",
    fontWeight: 600,
    color: colors.textDark,
    margin: "0 0 20px 0",
  },
  mediaGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(100px, 1fr))",
    gap: "15px",
  },
  mediaItem: {
    position: "relative",
    paddingTop: "100%",
    borderRadius: "8px",
    overflow: "hidden",
    cursor: "pointer",
    background: colors.border,
  },
  mediaThumbnail: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    transition: "transform 0.3s ease",
  },
  playIcon: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    fontSize: "2rem",
    color: "rgba(255,255,255,0.8)",
    zIndex: 1,
  },

  mediaViewerOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.85)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2000,
  },
  mediaViewerContent: {
    position: "relative",
    maxWidth: "80vw",
    maxHeight: "80vh",
  },
  mediaViewerMedia: {
    maxWidth: "100%",
    maxHeight: "100%",
    display: "block",
    borderRadius: "8px",
  },
  mediaViewerNav: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    background: "rgba(0,0,0,0.5)",
    color: "white",
    border: "none",
    borderRadius: "50%",
    width: "50px",
    height: "50px",
    fontSize: "24px",
    cursor: "pointer",
    zIndex: 2001,
  },

  actionsPanel: {
    backgroundColor: colors.white,
    padding: "30px",
    borderRadius: "12px",
    border: `1px solid ${colors.border}`,
    boxShadow: `0 4px 12px ${colors.shadow}`,
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  actionsTitle: {
    fontSize: "1.5rem",
    fontWeight: 600,
    color: colors.textDark,
    margin: "0 0 10px 0",
    textAlign: "center",
  },
  actionButton: {
    padding: "15px 25px",
    fontSize: "1rem",
    fontWeight: "bold",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.3s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
  },
  reinvestButton: { backgroundColor: colors.success, color: colors.white },
  downloadButton: { backgroundColor: colors.info, color: colors.white },
  toggleContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "15px",
    backgroundColor: "#f8f9fa",
    borderRadius: "8px",
  },
  toggleLabel: { fontWeight: 600, color: colors.textDark },
  switch: {
    position: "relative",
    display: "inline-block",
    width: "60px",
    height: "34px",
  },
  switchInput: { opacity: 0, width: 0, height: 0 },
  slider: {
    position: "absolute",
    cursor: "pointer",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#ccc",
    transition: ".4s",
    borderRadius: "34px",
  },
  sliderBefore: {
    position: "absolute",
    content: '""',
    height: "26px",
    width: "26px",
    left: "4px",
    bottom: "4px",
    backgroundColor: "white",
    transition: ".4s",
    borderRadius: "50%",
  },
  backLink: {
    display: "inline-block",
    marginTop: "30px",
    fontWeight: 600,
    color: colors.primary,
    textDecoration: "none",
  },
};

export default style;
